<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-S0433K5K" ignored="0" name="retryMultipleFailedTestCases" tests="9" failures="2" timestamp="2020-05-31T00:19:50 IST" time="0.12" errors="0">
  <testcase name="test1" time="0.015" classname="MyTest.MyTests1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="MyTest.MyTests1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="MyTest.MyTests1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="MyTest.MyTests1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at MyTest.MyTests1.test1(MyTests1.java:11)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="MyTest.MyTests1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="MyTest.MyTests1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="MyTest.MyTests1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="MyTest.MyTests1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at MyTest.MyTests1.test2(MyTests1.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.002" classname="MyTest.MyTests1"/>
</testsuite> <!-- retryMultipleFailedTestCases -->
